# Generated by Django 5.0.4 on 2024-04-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.CharField(default='user', max_length=200),
            preserve_default=False,
        ),
    ]
