# Generated by Django 5.0.4 on 2024-04-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0006_alter_rating_movie_alter_rating_out_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='out_of',
            field=models.IntegerField(default='5'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.IntegerField(),
        ),
    ]
